apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api-deployment
  labels:
    app: employee-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
      - name: employee-api
        image: siri2025/employee1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
