apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
spec:
  selector:
    app: employee-api
  type: NodePort       
  ports:
    - protocol: TCP
      port: 5000        
      targetPort: 5000  
      nodePort: 30001   
